const constants = {
	START_QUERY: "START_QUERY",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	CHANGE_NEXT_PAGE: 'CHANGE_NEXT_PAGE',
	RESET_CHANNELS : 'RESET_CHANNELS'
}

export default constants